import { withTyping } from '../lib/utils.js';
const helper = {
  command: ['dare'],
  category: 'tools',
  description: 'Send a random dare',
  operate: async (ctx) => {
    const dares = [
      "Send a voice note saying your name dramatically.",
      "Text your crush 'I dreamed about you 👀'.",
      "Use only emojis for the next 5 messages.",
      "Change your name to 'Clown' for 10 minutes 🤡.",
      "Send the most embarrassing photo in your gallery (if brave).",
      "Do 10 push-ups while singing a silly song.",
      "Sing a song in a funny voice.",
      "Show your best dance move.",
      "Tell a joke to the group.",
      "Let someone draw on your face with a marker.",
      "Do a funny impression of a celebrity.",
      "Eat something spicy or sour.",
      "Send a silly text to a friend.",
      "Do a 30-second handstand (if possible).",
      "Wear a silly hat or accessory for the rest of the game.",
      "Speak in a high-pitched voice for 5 minutes.",
      "Do 20 jumping jacks.",
      "Send a message using only your feet.",
      "Draw a funny picture and show it to everyone.",
      "Tell a secret anonymously (if in a group).",
      "Do a rap about your favorite food.",
      "Use only rhyming words for the next 3 messages.",
      "Tell everyone your favorite meme.",
      "Pretend to be a robot for 2 minutes.",
      "Do a dramatic reading of a random text.",
      "Make a funny animal sound.",
      "Change your profile picture to something silly.",
      "Write a short poem about a random object.",
      "Talk like a pirate for 5 minutes.",
      "Make a funny face and send it to someone.",
      "Do 10 squats while making animal noises.",
      "Send a random GIF to someone.",
      "Tell everyone your most irrational fear.",
      "Do a funny dance in front of a mirror.",
      "Change your WhatsApp status to something weird.",
      "Use only GIFs for the next 3 messages.",
      "Tell a random fun fact.",
      "Pretend to be a news anchor for 1 minute.",
      "Make a silly voice recording and send it.",
      "Send a message backwards.",
      "Do 5 funny poses for a photo.",
      "Tell everyone about your favorite childhood memory.",
      "Use only questions for the next 5 messages.",
      "Do a magic trick (if you know one).",
      "Send a funny joke to someone.",
      "Pretend to be a cat for 3 minutes.",
      "Make a funny sound effect and send it.",
      "Tell everyone something you're proud of.",
      "Change your keyboard theme to something funny.",
      "Do a funny voiceover for a short video.",
      "Send a message using only your nose.",
      "Tell a random story about yourself.",
      "Do 10 funny hops.",
      "Use only song lyrics for the next 3 messages.",
      "Pretend to be a superhero for 2 minutes.",
      "Make a funny face and take a selfie.",
      "Send a random word to someone and explain it.",
      "Do a funny walk in a circle.",
      "Tell everyone your favorite hobby.",
      "Change your name to something funny for 10 minutes.",
      "Use only emojis for the next 10 messages.",
      "Tell a random joke in a funny accent.",
      "Do a funny impression of an animal.",
      "Send a funny meme to someone.",
      "Pretend to be a famous person for 2 minutes.",
      "Make a funny sound and send it as a voice note.",
      "Tell everyone something you're grateful for.",
      "Do a funny dance and send it as a video.",
      "Change your WhatsApp bio to something silly.",
      "Use only funny words for the next 5 messages.",
      "Tell a random story about a friend.",
      "Do a funny pose and send a photo.",
      "Send a funny message to someone special."
    ];
    const msg = dares[Math.floor(Math.random() * dares.length)];
    await ctx.reply(`*I Dare you:* ${msg}`, { parse_mode: "Markdown" });
  }
};

export default helper;