const helper = {
  command: ['pickup'],
  category: 'tools',
  description: 'Send a random pickup line',
  operate: async (ctx) => {
    const lines = [
      "Are you WiFi? Because I'm feeling a connection.",
      "Do you believe in love at first sight—or should I send another message?",
      "Are you a keyboard? Because you're just my type.",
      "Is your name Google? You have everything I’m searching for.",
      "Are you a star? Because your beauty lights up my world.",
      "Excuse me, but I think you dropped something: my jaw.",
      "Do you have a map? I just keep getting lost in your eyes.",
      "Are you a magician? Every time I look at you, everyone else disappears.",
      "Do you believe in love at first sight, or should I walk by again?",
      "Are you an alien? Because you're out of this world.",
      "I must be a snowflake, because I’ve fallen for you.",
      "Do you have a sunburn or are you always this hot?",
      "Are you a time traveler? Because I see you in my future.",
      "I was wondering if you could help me. I’ve lost my number—can I have yours?",
      "Do you have a license? Because you're driving me crazy.",
      "If you were a vegetable, you’d be a ‘cute-cumber.’",
      "Are you a bank loan? Because you have my interest.",
      "Do you have a shovel? I just dug myself a hole after falling for you.",
      "Are you a parking ticket? Because you’ve got ‘fined’ all over you.",
      "Do you have a map? I keep getting lost in your eyes.",
      "Are you an exam? Because you make me nervous.",
      "Do you have a mirror? Your face is so beautiful.",
      "Are you a magician? You make everyone disappear.",
      "Do you have a thermometer? You’re on fire.",
      "Are you a camera? Every time I look at you, I smile.",
      "Do you have a library card? I’d like to check you out.",
      "Are you a time machine? I see you in my future.",
      "Do you have a broom? You’re sweeping me off my feet.",
      "Are you a genie? You make my dreams come true.",
      "Do you have a compass? You’re pointing me in the right direction.",
      "Are you a magician? You make my heart disappear.",
      "Do you have a map? I’m lost in your eyes.",
      "Are you a snowflake? You’re so unique and beautiful.",
      "Do you have a treasure map? You’re leading me to adventure.",
      "Are you a puzzle? You’re missing a piece—my heart.",
      "Do you have a key? You’re unlocking my heart.",
      "Are you a star? You’re shining bright.",
      "Do you have a ladder? You’re taking my breath away.",
      "Are you a dream? You’re too good to be true.",
      "Do you have a compass? You’re pointing me to love.",
      "Are you a treasure? You’re worth searching for.",
      "Do you have a mirror? You’re reflecting my feelings.",
      "Are you a gift? You’re wrapped up in awesomeness.",
      "Do you have a key? You’re unlocking my soul.",
      "Are you a song? You’re stuck in my head.",
      "Do you have a map? I’m lost in your eyes.",
      "Are you a book? You’re captivating.",
      "Do you have a camera? You’re picture-perfect.",
      "Are you a flower? You’re blooming beautiful.",
      "Do you have a sun? You’re lighting up my day.",
      "Are you a rainbow? You’re colorful and bright.",
      "Do you have a heart? You’re stealing mine.",
      "Are you a treasure chest? You’re full of surprises.",
      "Do you have a wish? Mine is to be with you.",
      "Are you a miracle? You’re amazing.",
      "Do you have a map? I’m navigating my way to you.",
      "Are you a dream come true? You’re incredible.",
      "Do you have a secret? Mine is that I like you.",
      "Are you a sweet treat? You’re making my heart smile.",
      "Do you have a love potion? You’re enchanting me.",
      "Are you a work of art? You’re a masterpiece.",
      "Do you have a compass? You’re guiding me to love.",
      "Are you a treasure? You’re worth finding.",
      "Do you have a heart? Mine is beating for you.",
      "You're a magician, making my heart disappear.",
      "Your eyes are like a work of art, a masterpiece.",
      "Do you have a magic wand? You're making magic happen.",
      "You're a treasure, hidden and waiting to be found.",
      "Your smile is contagious, and I'm infected.",
      "You're a dream come true, and I'm grateful.",
      "Do you have a time machine? You're taking me back to my best moments.",
      "You're a star, shining bright and beautiful.",
      "Do you have a map? I'm lost in your eyes, and I don't want to be found.",
      "You're a treasure, worth searching for and finding.",
      "Your eyes are like a work of art, a masterpiece.",
      "Do you have a magic wand? You're making magic happen.",
      "You're a treasure, hidden and waiting to be found.",
      "Your smile is contagious, and I'm infected.",
      "You're a dream come true, and I'm grateful.",
      "Do you have a time machine? You're taking me back to my best moments.",
      "You're a star, shining bright and beautiful.",
      "Do you have a map? I'm lost in your eyes, and I don't want to be found.",
      "You're a treasure, worth searching for and finding."
    ];
    await ctx.reply(lines[Math.floor(Math.random() * lines.length)]);
  }
};

export default helper;