const helper = {
  command: ["quote"],
  category: "tools",
  description: "Get a random motivational quote",
  operate: async (ctx) => {
    try {
      const quotes = [
        "The best way to get started is to quit talking and begin doing. — Walt Disney",
        "Don't let yesterday take up too much of today. — Will Rogers",
        "It's not whether you get knocked down, it's whether you get up. — Vince Lombardi",
        "You learn more from failure than from success. — Unknown",
        "The harder you work for something, the greater you'll feel when you achieve it. — Unknown",
        "Believe you can and you're halfway there. — Theodore Roosevelt",
        "The only way to do great work is to love what you do. — Steve Jobs",
        "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
        "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
        "You miss 100% of the shots you don't take. — Wayne Gretzky",
        "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
        "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
        "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
        "Do something today that your future self will thank you for. — Unknown",
        "Keep your eyes on the stars, and your feet on the ground. — Theodore Roosevelt",
        "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
        "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
        "Do what you can, with what you have, where you are. — Theodore Roosevelt",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. — Christian D. Larson",
        "You are stronger than you seem, braver than you believe, and smarter than you think. — Christopher Robin",
        "It does not matter how slowly you go as long as you do not stop. — Confucius",
        "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. — Albert Schweitzer",
        "The best revenge is massive success. — Frank Sinatra",
        "You don't need to be perfect, you just need to be better than you were yesterday. — Unknown",
        "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
        "Life is 10% what happens to you and 90% how you react to it. — Charles R. Swindoll",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
        "You are never too old to become the person you could have been. — George Eliot",
        "The way to get started is to quit talking and begin doing. — Walt Disney",
        "Life is really simple, but we insist on making it complicated. — Confucius",
        "The secret of getting ahead is getting started. — Mark Twain",
        "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
        "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
        "Opportunities don't happen, you create them. — Chris Grosser",
        "Don't let what you cannot do interfere with what you can do. — John Wooden",
        "The best way to predict the future is to create it. — Peter Drucker",
        "You are capable of amazing things. — Unknown",
        "Keep smiling, it makes a difference. — Unknown",
        "You got this! — Unknown",
        "Believe in yourself, you are amazing. — Unknown",
        "Stay positive, work hard, and make it happen. — Unknown",
        "The only bad workout is the one that didn't happen. — Joe Cirulli",
        "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
        "Motivation is what gets you started. Habit is what keeps you going. — Jim Rohn",
        "The pain you feel today will be the strength you feel tomorrow. — Unknown",
        "It always seems impossible until it's done. — Nelson Mandela",
        "You are one decision away from a totally different life. — Unknown",
        "The key is not to prioritize what's on your schedule, but to schedule your priorities. — Stephen Covey",
        "Don't wish for it, work for it. — Unknown",
        "The best is yet to come. — Robert Browning",
        "You are stronger than your excuses. — Unknown",
        "Chase your dreams, but never give up your spot. — Unknown",
        "Do it now, sometimes 'later' never comes. — Unknown",
        "The only way to do great work is to love what you do. — Steve Jobs",
        "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
        "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
        "Do something today that your future self will thank you for. — Unknown",
        "Keep your eyes on the stars, and your feet on the ground. — Theodore Roosevelt"
      ];
      const random = quotes[Math.floor(Math.random() * quotes.length)];
      await ctx.reply(random);
    } catch(e) {
      ctx.reply("Failed to fetch quote: " + e.message);
    }
  },
  noPrefix: false,
  isOwner: false,
  isGroup: false,
  isPremium: false,
};

export default helper;