import { withTyping } from '../lib/utils.js';
const helper = {
  command: ['truth'],
  category: 'tools',
  description: 'Send a random truth question',
  operate: async (ctx) => {
    const truths = [
      "What’s a secret you’ve never told anyone?",
      "Who was your first crush?",
      "Have you ever lied to impress someone?",
      "What’s the biggest mistake you’ve made?",
      "What’s something you’re afraid to admit?",
      "What’s the last thing you lied about?",
      "What’s the most childish thing you still do?",
      "Who’s the last person you’ve texted?",
      "What’s something you’ve done that you’re ashamed of?",
      "What’s your biggest regret?",
      "What’s your biggest fear?",
      "What’s something you’ve always wanted to try but haven’t?",
      "What’s the most embarrassing thing you’ve done?",
      "What’s your guilty pleasure?",
      "What’s something you’ve done that you’re not proud of?",
      "What’s your biggest insecurity?",
      "What’s something you’ve lied about on social media?",
      "What’s the most trouble you’ve ever gotten into?",
      "What’s something you’ve done that you got away with?",
      "What’s your favorite thing about yourself?",
      "What’s something you’re proud of?",
      "What’s your favorite hobby?",
      "What’s something you’re good at home?",
      "What’s something you’re not good at?",
      "What’s your favorite book/movie/TV show and why?",
      "What’s something you’ve always wanted to say to someone?",
      "What’s the most spontaneous thing you’ve ever done?",
      "What’s something you’ve done that you’re proud of?",
      "What’s your favorite way to spend a day off?",
      "What’s something you’ve learned recently?",
      "What’s your favorite food?",
      "What’s your favorite travel destination?",
      "What’s something you’re looking forward to?",
      "What’s something you’re grateful for?",
      "What’s your favorite way to relax?",
      "What’s something you’ve done that was out of character?",
      "What’s the best advice you’ve ever received?",
      "What’s something you’d like to change about yourself?",
      "What’s your favorite way to spend time with friends?",
      "What’s something you’ve done that you thought was going to get you in trouble?",
      "What’s the most embarrassing thing you’ve said to someone?",
      "What’s something you’ve done that you thought was cool at the time but now cringe at?",
      "What’s the most adventurous thing you’ve ever done?",
      "What’s something you’ve done that you’re glad you did?",
      "What’s something you’ve done that you wish you could take back?",
      "What’s your favorite way to spend a lazy day?",
      "What’s something you’ve done that was a bad idea?",
      "What’s the most interesting thing about you?",
      "What’s something you’ve done that you’re proud of?",
      "What’s your favorite way to spend time with family?",
      "What’s something you’ve done that was a surprise to everyone?",
      "What’s the most romantic thing you’ve ever done?",
      "What’s something you’ve done that you thought was going to be a disaster but turned out okay?",
      "What’s the most spontaneous thing you’ve ever done?",
      "What’s something you’ve done that you’re glad you didn’t do sooner?",
      "What’s the best decision you’ve ever made?",
      "What’s something you’ve done that you’re proud of?",
      "What’s your favorite way to spend time with your pet?",
      "What’s something you’ve done that was a learning experience?",
      "What’s the most interesting thing you’ve learned recently?",
      "What’s something you’ve done that you’re proud of?",
      "What’s your favorite way to spend time with your friends?",
      "What’s something you’ve done that was a surprise to everyone?"
    ];
    const msg = truths[Math.floor(Math.random() * truths.length)];
    await ctx.reply(`*Truth:* ${msg}`, { parse_mode: "Markdown" });
  }
};

export default helper;